[project]
name = "lora_finetune"
version = "0.2.0"
description = "lora_finetune"
requires-python = ">=3.8"
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
    "dataclasses",
    "typing"
]